
os: 
- linux 
- osx 

language: 
- cpp 
 
compiler: 
- gcc 
addons: 
apt: 
sources: 
- ubuntu-toolchain-r-test 
packages: 
- gcc-11 
script: 
- ln -s /usr/bin/gcc-11 /usr/local/bin/gcc 
- export CC=/usr/bin/gcc11

script: make Stack
