
os: 
- linux 
- osx 

language: 
- cpp 
compiler: 
- gcc-11
addons: 
apt: 
sources: 
- ubuntu-toolchain-r-test 
packages: 
- gcc-11
- g++-11 
- cmake 
script: 

- ln -s /usr/bin/gcc-11 /usr/local/bin/gcc 
- ln -s /usr/bin/g++-11 /usr/local/bin/g++ 
 
- export CC=/usr/bin/gcc-11
- export CXX=/usr/bin/g++-11

- gcc -v && g++ -v && cmake —version

script: make Stack
